# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments:         true

# Permalinks
permalink:        pretty
baseurl:          /neubertify

# Setup
title:            Neubertify
tagline:          'Get neubertified here.'
description:      'Learn about the source of neubertification on <a href="http://jonasneubert.com">jonasneubert.com</a><br><br>Neubertification in 140 characters or less is available at <a href="https://twitter.com/jonemo">twitter.com/jonemo</a>'
url:              http://jonemo.github.io/neubertify

author:
  name:           'Jonas Neubert'
  url:            http://jonasneubert.com

paginate:         5

