# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /neubertify

# Setup
title:            Neubertify
tagline:          'Get neubertified here.'
description:      'Learn about the source of neubertification on <a href="http://jonasneubert.com">jonasneubert.com</a><br><br>Neubertification in 140&nbsp;characters or less is available at <a href="https://twitter.com/jonemo">twitter.com/jonemo</a>'
url:              http://jonemo.github.io/neubertify

author:
  name:           'Jonas Neubert'
  url:            http://jonasneubert.com

paginate:         20

