# Dependencies
markdown:         kramdown
highlighter:      rouge

# SASS
sass:
  sass_dir:       _sass
  style:         :compressed

# Permalinks
permalink:        pretty
baseurl:          /

# Setup
title:            Neubertify
tagline:          'Get neubertified here.'
url:              "https://blog.jonasneubert.com"

analytics_id:     "UA-435125-11"
paginate:         20

author:
  name:           "Jonas Neubert"
  url:            "https://jonasneubert.com"

# Gems
gems:
  - jekyll-paginate
